from __future__ import annotations

import re
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SEO_OUT = ROOT / "outputs" / "usb-seo"
WORKBOOK = SEO_OUT / "usb_connectivity_keyword_architecture_full.xlsx"
CONTENT = ROOT / "astro" / "src" / "content" / "site"
REPORT = ROOT / "strategy" / "FULL_PROJECT_COMPLETION_AUDIT.md"
AUDIT_BOOK = SEO_OUT / "project_completion_audit.xlsx"


def read_routes() -> list[str]:
    routes: list[str] = []
    for path in sorted(CONTENT.glob("*.md")):
        match = re.search(r'^route:\s*["\']?([^"\'\n]+)', path.read_text(encoding="utf-8"), re.M)
        if match:
            routes.append(match.group(1).strip())
    return routes


def main() -> None:
    xls = pd.ExcelFile(WORKBOOK)
    blueprint = pd.read_excel(WORKBOOK, sheet_name="SERP_Content_Blueprint")
    validation = pd.read_excel(
        SEO_OUT / "usb_full_architecture_validation.xlsx",
        sheet_name="Validation_Checks",
    )
    planned = sorted(set(blueprint["url_slug"].dropna().astype(str)))
    actual = read_routes()
    actual_content = sorted(route for route in actual if route not in {"/", "/privacy/", "/terms/", "/get-a-quote/", "/request-sample/"})
    overlap = sorted(set(planned) & set(actual_content))
    missing = sorted(set(planned) - set(actual_content))
    prototype_only = sorted(set(actual_content) - set(planned))

    gates = pd.DataFrame(
        [
            ("Keyword cleaning and mapping", "PASS", "8,118 keyword rows in the canonical 21-sheet workbook"),
            ("Architecture workbook structure", "PASS", f"{len(xls.sheet_names)} required sheets present"),
            ("Local architecture validation", "PASS", f"{int((validation['status'].astype(str).str.lower() == 'pass').sum())}/{len(validation)} checks pass"),
            ("Full dashboard export", "PASS" if (SEO_OUT / "usb_connectivity_seo_dashboard.html").exists() else "FAIL", "Canonical dashboard is served on port 8602"),
            ("Planned SEO route implementation", "INCOMPLETE", f"{len(overlap)}/{len(planned)} planned routes currently match content routes"),
            ("Embedding semantic validation", "BLOCKED", "44/44 pages remain pending-embedding; external transmission requires explicit authorization"),
            ("Live top-10 SERP validation", "BLOCKED", "44/44 pages remain on hold until live SERP evidence is captured"),
            ("Business evidence and RFQ integration", "BLOCKED", "Identity, product evidence, commercial terms and RFQ destination are not supplied"),
            ("Public launch gate", "BLOCKED", "Private-review/noindex remains correctly active"),
            ("Git/GitNexus project history", "INCOMPLETE", "No valid indexed Git repository is available"),
        ],
        columns=["Area", "Status", "Evidence"],
    )

    route_rows = []
    route_rows += [(r, "implemented-planned") for r in overlap]
    route_rows += [(r, "planned-not-implemented") for r in missing]
    route_rows += [(r, "prototype-only-review") for r in prototype_only]
    routes = pd.DataFrame(route_rows, columns=["Route", "Status"])

    with pd.ExcelWriter(AUDIT_BOOK, engine="openpyxl") as writer:
        gates.to_excel(writer, index=False, sheet_name="Completion_Gates")
        routes.to_excel(writer, index=False, sheet_name="Route_Gap")

    gate_lines = "\n".join(f"| {row.Area} | {row.Status} | {row.Evidence} |" for row in gates.itertuples())
    missing_lines = "\n".join(f"- `{route}`" for route in missing)
    extra_lines = "\n".join(f"- `{route}`" for route in prototype_only)
    REPORT.write_text(
        f"""# Full Project Completion Audit

Generated by `usb-connectivity-seo/audit_project_completion.py`.

## Verdict

The keyword system and full dashboard are structurally complete, but the overall project is **not complete or publish-ready**. Only {len(overlap)} of {len(planned)} planned SEO routes currently match implemented content routes. External semantic/SERP evidence and business evidence remain gated.

## Completion gates

| Area | Status | Evidence |
|---|---|---|
{gate_lines}

## Route coverage

- Planned SEO routes: {len(planned)}
- Current content routes excluding utility pages: {len(actual_content)}
- Exact planned/implemented matches: {len(overlap)}
- Planned routes not implemented: {len(missing)}
- Prototype-only routes requiring retain/redirect/merge review: {len(prototype_only)}

### Planned but not implemented

{missing_lines or '- None'}

### Prototype-only routes

{extra_lines or '- None'}

## Publication rule

Keep all pages in `private-review` with `noindex` until every blocked gate has evidence and approval. A successful local build is not publication approval.
""",
        encoding="utf-8",
    )
    print(f"Wrote {REPORT}")
    print(f"Wrote {AUDIT_BOOK}")
    print(f"route coverage: {len(overlap)}/{len(planned)}; missing={len(missing)}; prototype_only={len(prototype_only)}")


if __name__ == "__main__":
    main()
